import { NextResponse } from 'next/server';

export async function GET(req) {
    const { searchParams } = new URL(req.url);
    const snow = parseFloat(searchParams.get('q2')) || 0; // Get average rainfall

    const countriesWithRegularSnowfall = [
        "Afghanistan",
        "Albania",
        "Andorra",
        "Armenia",
        "Austria",
        "Azerbaijan",
        "Belarus",
        "Belgium",
        "Bhutan",
        "Bosnia and Herzegovina",
        "Bulgaria",
        "Canada",
        "Chile",
        "China",
        "Croatia",
        "Czech Republic",
        "Denmark",
        "Estonia",
        "Finland",
        "France",
        "Georgia",
        "Germany",
        "Greece",
        "Hungary",
        "Iceland",
        "India",
        "Iran",
        "Ireland",
        "Italy",
        "Japan",
        "Kazakhstan",
        "Kosovo",
        "Kyrgyzstan",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macedonia",
        "Moldova",
        "Mongolia",
        "Montenegro",
        "Nepal",
        "Netherlands",
        "New Zealand",
        "North Korea",
        "Norway",
        "Pakistan",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "South Korea",
        "Spain",
        "Sweden",
        "Switzerland",
        "Tajikistan",
        "Turkey",
        "Turkmenistan",
        "Ukraine",
        "United Kingdom",
        "United States",
        "Uzbekistan"
    ];
      
    const countriesWithRareOrNoSnowfall = [
        "Antigua and Barbuda",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belize",
        "Benin",
        "Brunei",
        "Burkina Faso",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Cape Verde",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Congo",
        "Costa Rica",
        "Cuba",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Fiji",
        "Gabon",
        "Gambia",
        "Ghana",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "India",
        "Indonesia",
        "Israel",
        "Jamaica",
        "Jordan",
        "Kenya",
        "Kiribati",
        "Kuwait",
        "Laos",
        "Lebanon",
        "Liberia",
        "Libya",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Micronesia",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Oman",
        "Palau",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Qatar",
        "Rwanda",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Swaziland",
        "Tanzania",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Tuvalu",
        "Uganda",
        "United Arab Emirates",
        "Uruguay",
        "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe"
    ];

    try {
        if (snow === 0) {
            const response = [...countriesWithRareOrNoSnowfall, ...countriesWithRegularSnowfall].sort();
            const countriesSet = new Set(response); // Remove duplicates
            return NextResponse.json([...countriesSet]);
        }
        else {
            return NextResponse.json(countriesWithRegularSnowfall);
        }
    } catch (error) {
        console.error("Error fetching snow data:", error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}